'use client';
import {useEffect,useRef,useState} from 'react';
const workspace=[
 {title:'Welcome to Meridian',target:'.page-heading',text:'Start with one currency pair and one strategy. Meridian explains which rules match the chart; a matching setup is not a prediction or a command to trade.',tip:'This walkthrough highlights each feature. Use Next and Back, or Escape to leave.'},
 {title:'1. Choose a pair and timeframe',target:'.market-heading',text:'Pick EUR/USD, GBP/USD or USD/JPY. Intraday shows 15-minute candles; Swing shows 4-hour candles. A candle summarizes the opening, highest, lowest and closing price for that period.',tip:'Use the watchlist for quick pair switching. Manage watchlist adds or removes saved pairs.'},
 {title:'2. Pick a strategy',target:'.strategy-picker',text:'Start with Trend pullback. Each strategy has its own checklist and lesson. Changing strategies evaluates the same market candles, so you can compare their rules.',tip:'The Learn the strategy section explains terms, exact rules and limitations.'},
 {title:'3. Explore the chart',target:'.chart-panel',text:'Move your pointer over candles to inspect prices. With the chart focused, use the left and right arrow keys. EMA 20 and EMA 50 are moving-average lines; their checkboxes show or hide them.',tip:'Only completed candles are evaluated. Refresh data requests an update; the five-minute cache may reuse the previous response.'},
 {title:'4. Read the evidence',target:'.analysis-panel',text:'Bullish means an upward setup; bearish means a downward setup. PASS and FAIL show which conditions match. Open Show price evidence to see the numbers behind each check.',tip:'No matching setup is a useful result. Insufficient data means at least 200 completed candles are not available yet.'},
 {title:'You are ready to explore',target:'.workspace-menu',text:'Try a pair, choose Trend pullback and read the first unmet condition. Chart review is a separate page for your screenshots. You can replay the guide anytime with Help & tour.',tip:'Your watchlist and preferences are saved in this browser. AI and rule-based checks can be wrong; verify the chart before making a decision.'}
];
const review=[
 {title:'Review your own chart',target:'.page-heading',text:'This page uses AI to read a screenshot and explain possible conditional setups. It does not know current market prices just from an image.',tip:'Use Next and Back to learn the controls. Skip or Escape closes the guide.'},
 {title:'1. Choose a clear screenshot',target:'.upload-drop',text:'Choose a file or drag it into the upload area. PNG, JPEG and WebP images up to 5 MB are supported. Keep the price axis and timeframe visible.',tip:'Crop out account numbers, balances and other private details before uploading.'},
 {title:'2. Add useful context',target:'.upload-context',text:'Enter the pair, timeframe and when the screenshot was taken if these are not clear. You can preview or remove the selected screenshot before sending it.',tip:'For example: EUR/USD, 15-minute chart, captured at 10:30 UTC.'},
 {title:'3. Request a review',target:'.upload-actions',text:'Analyze chart sends the screenshot and your context to our AI provider. Wait for the result, or use Cancel to stop waiting. If AI is not configured, the button stays unavailable.',tip:'Cancelling may not stop processing that has already begun. Meridian does not save your image or review.'},
 {title:'4. Understand the possible setup',target:'.upload-results',text:'Entry is a conditional starting price. Stop loss (SL) is the proposed exit if the idea fails. Take profit (TP) is a proposed target. Read the confirmation trigger, evidence and invalidation before considering the levels.',tip:'Reward/risk compares price distances, not the chance of winning. AI can misread numbers; verify every level. No clear setup is a valid outcome.'},
 {title:'Keep learning',target:'.workspace-menu',text:'Return to Market workspace to explore strategy checklists and lessons. Use Help & tour anytime to replay this page’s guide.',tip:'A screenshot review is separate from the market workspace and does not place trades.'}
];
export default function Tutorial({reviewPage}:{reviewPage:boolean}){
 const steps=reviewPage?review:workspace;const key='meridian.tour.v1.'+(reviewPage?'review':'workspace');
 const [step,setStep]=useState<number|null>(null);const dialog=useRef<HTMLDialogElement>(null);const trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{try{if(localStorage.getItem(key)!=='seen')setStep(0);}catch{/* Help remains available when storage is blocked. */}},[key]);
 useEffect(()=>{if(step===null)return;const node=dialog.current;if(!node)return;if(!node.open)node.showModal();const target=document.querySelector(steps[step].target);target?.classList.add('tour-highlight');target?.scrollIntoView({behavior:'instant',block:'center'});return()=>{target?.classList.remove('tour-highlight');};},[step,steps]);
 function close(){try{localStorage.setItem(key,'seen');}catch{}dialog.current?.close();setStep(null);trigger.current?.focus({preventScroll:true});}
 return <><button ref={trigger} className="quiet tour-launch" onClick={()=>setStep(0)}>Help &amp; tour</button><dialog ref={dialog} className="tour-dialog" aria-labelledby="tour-title" aria-describedby="tour-copy" onCancel={e=>{e.preventDefault();close();}}>
 {step!==null&&<><div className="tour-top"><span className="eyebrow">QUICK START · {step+1} OF {steps.length}</span><button className="quiet" onClick={close} aria-label="Close tutorial">Skip tour</button></div><div aria-live="polite" aria-atomic="true"><h2 id="tour-title">{steps[step].title}</h2><p id="tour-copy">{steps[step].text}</p><p className="tour-tip">{steps[step].tip}</p></div><div className="tour-bottom"><span aria-hidden="true">{steps.map((_,i)=><span key={i} className={i===step?'tour-dot current':'tour-dot'}/>)}</span><div><button className="quiet" disabled={step===0} onClick={()=>setStep(step-1)}>Back</button><button className="quiet tour-next" onClick={()=>step===steps.length-1?close():setStep(step+1)}>{step===steps.length-1?'Get started':'Next →'}</button></div></div></>}
 </dialog></>;
}
